name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Get Tag
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${{ github.ref }} | cut -d / -f 3)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm install -g pkg
      - name: Create binaries
        run: pkg -o gh-insights -t node12-linux-x64,node12-macos-x64,node12-win-x64 index.js
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            gh-insights-linux
            gh-insights-macos
            gh-insights-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
